### ISSUE TITLE
Dashboard not showing service as stopped

### ISSUE THREAD

**Issue by corndog2000** [ratibor78/srvstatus#14] opened 2021-03-15 03:33 UTC
I have a service that I added to the list in the settings.ini file but when I stop the service with systemctl stop the dashboard keeps showing the latest uptime up until I stopped it. The status block keeps showing "UP".

I think this was caused by me migrating each block to the new, non-depreciated, stats panel.

**Comment by corndog2000** [comment] 2021-03-15 03:45
Is there anything I need to adjust in the dashboard panels after migrating them to statistics panels to restore desired functionality?

**Comment by ratibor78** [comment] 2021-03-15 07:50
Hi @corndog2000, you can check the status of the services that srvstatus send, by running the 

telegraf --test 

services_stats,host=myhost.com,service=docker.service status=1,status_time=4184281 1615794179000000000

for example, then you'll see which numeric value sending to the influxDB. 

I'm not sure about your issue with the Grafana dashboard, you need to make sure that your new Grafana dashboard still used the right database and so on. This issue does not really concern the srvstatus script, but mostly like to the Grafana/InfluxDb theme.

**Comment by corndog2000** [comment] 2021-03-15 18:19
Looking at the query inspector in grafana it doesn't seem to be getting an entry in influxdb that says the service is down. The database stops getting new entries after I stop the script. Here is the query request from the inspector. You can see a few entries with 1 instead of null and I'm assuming that's how the dashboard knows that the script is running? But, the database never gets information that the script is stopped. Looking at the grafana dashboard it is trying to see if the database gets a value of 3 to say the script is down. But, no entry with value of 3 is ever put into the database.

[Query request pastebin
](https://pastebin.com/n5crJGf3)
![image](https://user-images.githubusercontent.com/7349261/111202151-f01f3680-8599-11eb-85eb-a72617c0150a.png)

**Comment by corndog2000** [comment] 2021-03-15 19:22
I discovered a clue that might be related to the problems I'm having. If I add nodered.service to my settings.ini file and update the grafana dashboard to display nodered's status and time. Then, if nodered is running it shows as UP and the uptime starts to increase. When I stop the service it switches to DOWN. Here is where the issue is. If I run `sudo systemctl disable nodered.service` then when I stop the service the dashboard does not switch to DOWN. It stays as UP, but the uptime doesn't keep increasing.

So, it appears this python code only works for services that are enabled with systemctl such that they start on boot. Is there a way to adjust the python script to fix this?

**Comment by ratibor78** [comment] 2021-03-15 20:11
Well, this script grep the "systemctl status service" command and search these statuses:

  active (running) = 1
  active (exited) = 2
  inactive (dead) = 3
  failed  = 4
  no match = 0

So if your `systemctl status nodered.service` command showing one of these statuses it will be sent to the influxdb by the telegraf. 

Can you please provide me with the output of the `telegraf --test | grep nodered` when the service UP and then when you stop it. 

I tried to disable the docker service for example, and it still has the `Active: inactive (dead)` string in systemctl output also the script still generates the 3 into the DB.

**Comment by corndog2000** [comment] 2021-03-15 20:21
Here is `telegraf --test | grep nodered` when nodered is STARTED and ENABLED:
```
2021-03-15T20:17:23Z I! Starting Telegraf 1.17.3
2021-03-15T20:17:23Z I! Using config file: /etc/telegraf/telegraf.conf
> services_stats,host=SP-raspberrypi,service=nodered.service status=1,status_time=3 1615839445000000000
```


Here is `telegraf --test | grep nodered` when nodered is STOPPED and ENABLED:
```
2021-03-15T20:19:13Z I! Starting Telegraf 1.17.3
2021-03-15T20:19:13Z I! Using config file: /etc/telegraf/telegraf.conf
> services_stats,host=SP-raspberrypi,service=nodered.service status=3,status_time=2 1615839555000000000
```


Here is `telegraf --test | grep nodered` when nodered is STARTED and DISABLED:
```
2021-03-15T20:20:02Z I! Starting Telegraf 1.17.3
2021-03-15T20:20:02Z I! Using config file: /etc/telegraf/telegraf.conf
> services_stats,host=SP-raspberrypi,service=nodered.service status=1,status_time=7 1615839603000000000
```


**Here is `telegraf --test | grep nodered` when nodered is STOPPED and DISABLED:**
```
2021-03-15T20:20:27Z I! Starting Telegraf 1.17.3
2021-03-15T20:20:27Z I! Using config file: /etc/telegraf/telegraf.conf
```

You can see that when the service is STOPPED and DISABLED the telegraf script doesn't get any service status.

**Comment by ratibor78** [comment] 2021-03-15 20:34
Yep, I see the issue, can you please also provide the full output of the `systemctl status nodered` command when the service STOPPED and DISABLED and also STARTED and DISABLED. 

Thanks. I will try to reproduce this situation then.

**Comment by corndog2000** [comment] 2021-03-15 20:37
Here it is when STARTED and DISABLED
```
● nodered.service - Node-RED graphical event wiring tool
   Loaded: loaded (/lib/systemd/system/nodered.service; disabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-03-15 16:28:11 EDT; 7min ago
     Docs: http://nodered.org/docs/hardware/raspberrypi.html
 Main PID: 23992 (node)
    Tasks: 11 (limit: 4915)
   CGroup: /system.slice/nodered.service
           └─23992 node-red

Mar 15 16:28:19 SP-raspberrypi Node-RED[23992]: If the system-generated key is lost for any reason, your credentials
Mar 15 16:28:19 SP-raspberrypi Node-RED[23992]: file will not be recoverable, you will have to delete it and re-enter
Mar 15 16:28:19 SP-raspberrypi Node-RED[23992]: your credentials.
Mar 15 16:28:19 SP-raspberrypi Node-RED[23992]: You should set your own key using the 'credentialSecret' option in
Mar 15 16:28:19 SP-raspberrypi Node-RED[23992]: your settings file. Node-RED will then re-encrypt your credentials
Mar 15 16:28:19 SP-raspberrypi Node-RED[23992]: file using your chosen key the next time you deploy a change.
Mar 15 16:28:19 SP-raspberrypi Node-RED[23992]: ---------------------------------------------------------------------
Mar 15 16:28:19 SP-raspberrypi Node-RED[23992]: 15 Mar 16:28:19 - [info] Starting flows
Mar 15 16:28:19 SP-raspberrypi Node-RED[23992]: error ENOENT: no such file or directory, access '/home/pi/Documents/CANDB.kcd'
Mar 15 16:28:19 SP-raspberrypi Node-RED[23992]: 15 Mar 16:28:19 - [info] Started flows
```

And here is the output when STOPPED and DISABLED
```
● nodered.service - Node-RED graphical event wiring tool
   Loaded: loaded (/lib/systemd/system/nodered.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: http://nodered.org/docs/hardware/raspberrypi.html

Mar 15 16:28:19 SP-raspberrypi Node-RED[23992]: file using your chosen key the next time you deploy a change.
Mar 15 16:28:19 SP-raspberrypi Node-RED[23992]: ---------------------------------------------------------------------
Mar 15 16:28:19 SP-raspberrypi Node-RED[23992]: 15 Mar 16:28:19 - [info] Starting flows
Mar 15 16:28:19 SP-raspberrypi Node-RED[23992]: error ENOENT: no such file or directory, access '/home/pi/Documents/CANDB.kcd'
Mar 15 16:28:19 SP-raspberrypi Node-RED[23992]: 15 Mar 16:28:19 - [info] Started flows
Mar 15 16:37:06 SP-raspberrypi systemd[1]: Stopping Node-RED graphical event wiring tool...
Mar 15 16:37:06 SP-raspberrypi Node-RED[23992]: 15 Mar 16:37:06 - [info] Stopping flows
Mar 15 16:37:06 SP-raspberrypi Node-RED[23992]: 15 Mar 16:37:06 - [info] Stopped flows
Mar 15 16:37:06 SP-raspberrypi systemd[1]: nodered.service: Succeeded.
Mar 15 16:37:06 SP-raspberrypi systemd[1]: Stopped Node-RED graphical event wiring tool.
```

**Comment by ratibor78** [comment] 2021-03-15 20:50
Hmm, in the first output all looks OK, `Active: active (running) ` so the script sends the right status = 1, and in the second output **STOPPED and DISABLED** there also the `Active: inactive (dead)` status, but as I can see from your previous message the script doesn't find this string. 

Strange, thanks a lot for the additional information, I'll try to reproduce this situation and fix this issue. 

Maybe I'll need extra communication later if I'll be not able to reproduce this bug. Thanks once more @corndog2000

**Comment by corndog2000** [comment] 2021-03-15 20:51
You're welcome! I'll be available for any additional information to help fix this issue.

**Comment by ratibor78** [comment] 2021-03-16 16:08
HI, @corndog2000, looks like I reproduced this bug, but it seems that this situation can be only if you disable the service and then reboot the system so there no `since ` date are available in the ` Active: inactive (dead)` string. 

My script needs this `since` string with the date to be able to calculate the time from which the service failed. 

Well, I guess I can try to fix it, but I'll need to rewrite all script parsing logic.

**Comment by ratibor78** [comment] 2021-03-20 12:10
Hi @corndog2000 I have fixed the issue with the parsing of the DISABLED services.

Now, the **srvstatus** will parse the service and send the right status code with the `since time` = 0 even if the service was ENABLED and then DISABLED and the system was restarted. The `since time` will be zero as there will be no date at all in this situation.  

Merged and ready to use. Hope it'll be more useful for you. Please test it and if the bug is gone, I'll close the issue then.

**Comment by ratibor78** [comment] 2021-03-22 12:02
Well, I'll close this issue as fixed, we can reopen it after.

**Closed as completed by ratibor78** 2021-03-22 12:02 UTC
